//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.07 at 04:24:31 PM EST 
//


package copath2cytolink.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Case">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CaseDetailsSet">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CaseDetail" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="ctrltype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="mandatory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ScanSlide">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ScanDetailsSet">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="SlideDetail" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="ctrltype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="mandatory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="barcode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="templatename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "_case"
})
@XmlRootElement(name = "CWS")
public class CWS {

    @XmlElement(name = "Case", required = true)
    protected CWS.Case _case;

    /**
     * Gets the value of the case property.
     * 
     * @return
     *     possible object is
     *     {@link CWS.Case }
     *     
     */
    public CWS.Case getCase() {
        return _case;
    }

    /**
     * Sets the value of the case property.
     * 
     * @param value
     *     allowed object is
     *     {@link CWS.Case }
     *     
     */
    public void setCase(CWS.Case value) {
        this._case = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CaseDetailsSet">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CaseDetail" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="ctrltype" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="mandatory" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ScanSlide">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ScanDetailsSet">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="SlideDetail" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="ctrltype" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="mandatory" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="barcode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="templatename" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "caseDetailsSet",
        "scanSlide"
    })
    public static class Case {

        @XmlElement(name = "CaseDetailsSet", required = true)
        protected CWS.Case.CaseDetailsSet caseDetailsSet;
        @XmlElement(name = "ScanSlide", required = true)
        protected CWS.Case.ScanSlide scanSlide;
        @XmlAttribute(name = "name")
        protected String name;

        /**
         * Gets the value of the caseDetailsSet property.
         * 
         * @return
         *     possible object is
         *     {@link CWS.Case.CaseDetailsSet }
         *     
         */
        public CWS.Case.CaseDetailsSet getCaseDetailsSet() {
            return caseDetailsSet;
        }

        /**
         * Sets the value of the caseDetailsSet property.
         * 
         * @param value
         *     allowed object is
         *     {@link CWS.Case.CaseDetailsSet }
         *     
         */
        public void setCaseDetailsSet(CWS.Case.CaseDetailsSet value) {
            this.caseDetailsSet = value;
        }

        /**
         * Gets the value of the scanSlide property.
         * 
         * @return
         *     possible object is
         *     {@link CWS.Case.ScanSlide }
         *     
         */
        public CWS.Case.ScanSlide getScanSlide() {
            return scanSlide;
        }

        /**
         * Sets the value of the scanSlide property.
         * 
         * @param value
         *     allowed object is
         *     {@link CWS.Case.ScanSlide }
         *     
         */
        public void setScanSlide(CWS.Case.ScanSlide value) {
            this.scanSlide = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CaseDetail" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="ctrltype" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="mandatory" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "caseDetail"
        })
        public static class CaseDetailsSet {

            @XmlElement(name = "CaseDetail")
            protected List<CWS.Case.CaseDetailsSet.CaseDetail> caseDetail;

            /**
             * Gets the value of the caseDetail property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the caseDetail property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCaseDetail().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CWS.Case.CaseDetailsSet.CaseDetail }
             * 
             * 
             */
            public List<CWS.Case.CaseDetailsSet.CaseDetail> getCaseDetail() {
                if (caseDetail == null) {
                    caseDetail = new ArrayList<CWS.Case.CaseDetailsSet.CaseDetail>();
                }
                return this.caseDetail;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="ctrltype" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="mandatory" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class CaseDetail {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "title")
                protected String title;
                @XmlAttribute(name = "text")
                protected String text;
                @XmlAttribute(name = "type")
                protected String type;
                @XmlAttribute(name = "ctrltype")
                protected String ctrltype;
                @XmlAttribute(name = "editable")
                protected String editable;
                @XmlAttribute(name = "mandatory")
                protected String mandatory;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the title property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTitle() {
                    return title;
                }

                /**
                 * Sets the value of the title property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTitle(String value) {
                    this.title = value;
                }

                /**
                 * Gets the value of the text property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getText() {
                    return text;
                }

                /**
                 * Sets the value of the text property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setText(String value) {
                    this.text = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the ctrltype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCtrltype() {
                    return ctrltype;
                }

                /**
                 * Sets the value of the ctrltype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCtrltype(String value) {
                    this.ctrltype = value;
                }

                /**
                 * Gets the value of the editable property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEditable() {
                    return editable;
                }

                /**
                 * Sets the value of the editable property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEditable(String value) {
                    this.editable = value;
                }

                /**
                 * Gets the value of the mandatory property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMandatory() {
                    return mandatory;
                }

                /**
                 * Sets the value of the mandatory property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMandatory(String value) {
                    this.mandatory = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ScanDetailsSet">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="SlideDetail" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="ctrltype" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="mandatory" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="barcode" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="templatename" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "scanDetailsSet"
        })
        public static class ScanSlide {

            @XmlElement(name = "ScanDetailsSet", required = true)
            protected CWS.Case.ScanSlide.ScanDetailsSet scanDetailsSet;
            @XmlAttribute(name = "barcode")
            protected String barcode;
            @XmlAttribute(name = "templatename")
            protected String templatename;

            /**
             * Gets the value of the scanDetailsSet property.
             * 
             * @return
             *     possible object is
             *     {@link CWS.Case.ScanSlide.ScanDetailsSet }
             *     
             */
            public CWS.Case.ScanSlide.ScanDetailsSet getScanDetailsSet() {
                return scanDetailsSet;
            }

            /**
             * Sets the value of the scanDetailsSet property.
             * 
             * @param value
             *     allowed object is
             *     {@link CWS.Case.ScanSlide.ScanDetailsSet }
             *     
             */
            public void setScanDetailsSet(CWS.Case.ScanSlide.ScanDetailsSet value) {
                this.scanDetailsSet = value;
            }

            /**
             * Gets the value of the barcode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBarcode() {
                return barcode;
            }

            /**
             * Sets the value of the barcode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBarcode(String value) {
                this.barcode = value;
            }

            /**
             * Gets the value of the templatename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTemplatename() {
                return templatename;
            }

            /**
             * Sets the value of the templatename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTemplatename(String value) {
                this.templatename = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="SlideDetail" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="ctrltype" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="mandatory" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "slideDetail"
            })
            public static class ScanDetailsSet {

                @XmlElement(name = "SlideDetail")
                protected List<CWS.Case.ScanSlide.ScanDetailsSet.SlideDetail> slideDetail;

                /**
                 * Gets the value of the slideDetail property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the slideDetail property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getSlideDetail().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link CWS.Case.ScanSlide.ScanDetailsSet.SlideDetail }
                 * 
                 * 
                 */
                public List<CWS.Case.ScanSlide.ScanDetailsSet.SlideDetail> getSlideDetail() {
                    if (slideDetail == null) {
                        slideDetail = new ArrayList<CWS.Case.ScanSlide.ScanDetailsSet.SlideDetail>();
                    }
                    return this.slideDetail;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="ctrltype" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="mandatory" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class SlideDetail {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "title")
                    protected String title;
                    @XmlAttribute(name = "text")
                    protected String text;
                    @XmlAttribute(name = "type")
                    protected String type;
                    @XmlAttribute(name = "ctrltype")
                    protected String ctrltype;
                    @XmlAttribute(name = "editable")
                    protected String editable;
                    @XmlAttribute(name = "mandatory")
                    protected String mandatory;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the title property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTitle() {
                        return title;
                    }

                    /**
                     * Sets the value of the title property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTitle(String value) {
                        this.title = value;
                    }

                    /**
                     * Gets the value of the text property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getText() {
                        return text;
                    }

                    /**
                     * Sets the value of the text property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setText(String value) {
                        this.text = value;
                    }

                    /**
                     * Gets the value of the type property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getType() {
                        return type;
                    }

                    /**
                     * Sets the value of the type property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setType(String value) {
                        this.type = value;
                    }

                    /**
                     * Gets the value of the ctrltype property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCtrltype() {
                        return ctrltype;
                    }

                    /**
                     * Sets the value of the ctrltype property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCtrltype(String value) {
                        this.ctrltype = value;
                    }

                    /**
                     * Gets the value of the editable property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getEditable() {
                        return editable;
                    }

                    /**
                     * Sets the value of the editable property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setEditable(String value) {
                        this.editable = value;
                    }

                    /**
                     * Gets the value of the mandatory property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getMandatory() {
                        return mandatory;
                    }

                    /**
                     * Sets the value of the mandatory property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setMandatory(String value) {
                        this.mandatory = value;
                    }

                }

            }

        }

    }

}
